---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/aws-ia/pre-commit-hooks
    # To update run:
    # pre-commit autoupdate --freeze
    rev: f589397d337ddfceb8fd8a7a0c70d747e96e0e5f  # frozen: v1.1
    hooks:
      - id: aws-ia-meta-hook
